### ISSUE TITLE
"Object reference not set to an instance of an object." when trying to open a specific asset.

### ISSUE THREAD

**Issue by britiscurious** [iAmAsval/FModel#161]
1. Describe the bug

"Object reference not set to an instance of an object." is shown when trying to open a specific asset.

FModel version is 3.1.2.0
Fortnite version is 15.40

2. Steps to reproduce the behavior

Try to open:
FortniteGame/Plugins/GameFeatures/SaveTheWorld/Content/Heroes/Ninja/ItemDefinition/HID_Ninja_033_HalloweenNinja_SR_T01.uasset

3. Send logs

2021-02-17 20:17:57.359 - [FModel] [Assets] [Package] Searching for '/FortniteGame/Plugins/GameFeatures/SaveTheWorld/Content/Heroes/Ninja/ItemDefinition/HID_Ninja_033_HalloweenNinja_SR_T01.uasset's package
2021-02-17 20:17:57.429 - [FModel] [Assets] [Package] Searching for '/FortniteGame/Plugins/GameFeatures/SaveTheWorld/Content/UI/Foundation/Textures/Icons/Heroes/Ninja/Portrait/T-Ninja-HID-Ninja-033-HalloweenNinja-L.uasset's package
2021-02-17 20:17:57.492 - [FModel] [Assets] [Package] Searching for '/FortniteGame/Content/Items/ItemCategories.uasset's package
2021-02-17 20:17:57.501 - [FModel] [Assets] [Package] Searching for '/FortniteGame/Content/UI/Foundation/Textures/Icons/ItemTypes/T-Icon-Hero-Ninja-32.uasset's package
2021-02-17 20:17:57.533 - [FModel] [Assets] [Package] Searching for '/FortniteGame/Plugins/GameFeatures/SaveTheWorld/Content/Heroes/Ninja/GameplayDefinition/HGD_Ninja_033_HalloweenNinja.uasset's package
2021-02-17 20:17:57.567 - [FModel] [Assets] [Package] Searching for '/FortniteGame/Plugins/GameFeatures/SaveTheWorld/Content/Abilities/Player/Perks/Hero/FromtheDepths/Kit_Perk_H_FromtheDepths_T01.uasset's package
2021-02-17 20:17:57.627 - [FModel] [Assets] [Package] Searching for '/FortniteGame/Content/Abilities/Player/Ninja/Actives/CrescentKick/Kit_Ninja_CrescentKick.uasset's package
2021-02-17 20:17:57.629 - [FModel] [Assets] [Package] Searching for '/FortniteGame/Content/UI/Foundation/Textures/Icons/Heroes/Ninja/Icon-Ninja-CrescentKick-128.uasset's package
2021-02-17 20:17:57.634 - [FModel] [Assets] [Package] Searching for '/FortniteGame/Content/Abilities/Player/Ninja/Actives/SmokeBomb/Kit_Ninja_SmokeBomb.uasset's package
2021-02-17 20:17:57.636 - [FModel] [Assets] [Package] Searching for '/FortniteGame/Content/UI/Foundation/Textures/Icons/Heroes/Ninja/Icon-Ninja-SmokeBomb-128.uasset's package
2021-02-17 20:17:57.642 - [FModel] [Assets] [Package] Searching for '/FortniteGame/Content/Abilities/Player/Ninja/Actives/KunaiStorm/Kit_Ninja_KunaiStorm.uasset's package
2021-02-17 20:17:57.644 - [FModel] [Assets] [Package] Searching for '/FortniteGame/Content/UI/Foundation/Textures/Icons/Heroes/Ninja/Icon-Ninja-KunaiThrow-128.uasset's package
2021-02-17 20:17:57.656 - [FModel] [Task] [Exception]:
System.NullReferenceException: Object reference not set to an instance of an object.
   at FModel.Creator.Stats.Statistics.DrawStats(SKCanvas c, BaseIcon icon)
   at FModel.Creator.Creator.TryDrawIcon(String assetPath, FName[] exportTypes, IUExport[] exports)
   at FModel.Utils.Assets.GetPackage(ReaderEntry entry, String mount, Boolean loadContent)
   at FModel.Utils.Assets.<>c__DisplayClass3_0.<GetUserSelection>b__0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

4. Add screenshots

n.a.

**DO NOT** report issues to ask where is `<insert your favorite asset here>`.
**DO NOT** report issues if you have AES errors.
**DO NOT** report issues if your game is not up to date.

Without following the rules above, your issue will be closed without explanation.

**Comment by iAmAsval** [comment]
it's working fine
![image](https://user-images.githubusercontent.com/26126862/108256948-69279b80-715e-11eb-93ca-c62007412869.png)

**Comment by britiscurious** [comment]
I'll check my Fortnite installation. Only the HID_Ninja_033_HalloweenNinja_SR assets are affected. All others run without any problem. Great tool btw! Big Thx!

**Comment by iAmAsval** [comment]
try to update your fmodel from here https://ci.appveyor.com/project/iAmAsval/fmodel/branch/master/artifacts

**Comment by britiscurious** [comment]
That one works! (But should have a later version number than 3.1.2.0 😉)
