### ISSUE TITLE
FModel not compatable with EGL3

### ISSUE THREAD

**Issue by QPixel** [iAmAsval/FModel#165]
1. Describe the bug
    Because EGL3 creates a read-only drive, when FModel tries to run `File.ReadAllBytesAsync(utoc);` It returns an IOException of "The Media is write protected". FModel should be able to read utoc's without needing write permissions.
2. Steps to reproduce the behavior
Try to open FModel in the latest beta of EGL3s install directory
3. Send logs
   ``2021-03-16 00:08:49.597 - [FModel] [Task] [Exception]:
System.IO.IOException: The media is write protected. : 'D:\FortniteGame\Content\Paks\pakchunk9optional-WindowsClient.utoc'
   at System.IO.FileStream.SeekCore(SafeFileHandle fileHandle, Int64 offset, SeekOrigin origin, Boolean closeInvalidHandle)
   at System.IO.FileStream.ReadNativeAsync(Memory`1 destination, Int32 numBufferedBytesRead, CancellationToken cancellationToken)
   at System.IO.FileStream.ReadAsyncInternal(Memory`1 destination, CancellationToken cancellationToken, Int32& synchronousResult)
   at System.IO.FileStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.File.InternalReadAllBytesAsync(FileStream fs, Int32 count, CancellationToken cancellationToken)
   at FModel.Grabber.Paks.PaksGrabber.<>c.<<PopulateMenu>b__1_1>d.MoveNext() in H:\Code Stuff\FModel\FModel\Grabber\Paks\PaksGrabber.cs:line 204
--- End of stack trace from previous location where exception was thrown ---
   at FModel.Grabber.Paks.PaksGrabber.PopulateMenu() in H:\Code Stuff\FModel\FModel\Grabber\Paks\PaksGrabber.cs:line 32
   at FModel.MainWindow.Init() in H:\Code Stuff\FModel\FModel\MainWindow.xaml.cs:line 94``
4. Add screenshots
![image](https://user-images.githubusercontent.com/29050038/111270287-e8d54880-85ec-11eb-9210-3edd3a070982.png)
![image](https://user-images.githubusercontent.com/29050038/111270308-eecb2980-85ec-11eb-9a02-91dd6bf489bf.png)

**Comment by iAmAsval** [comment]
waiting for [this](https://media.discordapp.net/attachments/821161981738352681/821287186954977280/unknown.png) to be fixed
