### ISSUE TITLE
Error: Unable to read beyond the end of the stream.

### ISSUE THREAD

**Issue by MrGazdag** [iAmAsval/FModel#174]
For some reason, it tells me "Unable to read beyond the end of the stream"
[FModel-Log-2021-04-10.txt](https://github.com/iAmAsval/FModel/files/6290181/FModel-Log-2021-04-10.txt)
Relevant log part:
```
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at FModel.PakReader.Parsers.Objects.FVirtualTextureBuiltData..ctor(BinaryReader reader, Stream ubulk, Int64 bulkOffset)
   at FModel.PakReader.Parsers.Objects.FTexturePlatformData..ctor(PackageReader reader, Stream ubulk, Int64 bulkOffset)
   at FModel.PakReader.Parsers.Class.UTexture2D.Serialize(PackageReader reader, Stream ubulk, Int64 bulkOffset)
   at FModel.PakReader.Parsers.LegacyPackageReader..ctor(BinaryReader uasset, BinaryReader uexp, Stream ubulk)
   at FModel.PakReader.Pak.PakPackage.get_Exports()
   at FModel.PakReader.Package.GetExport[T]()
   at FModel.Utils.Assets.GetPackage(ReaderEntry entry, String mount, Boolean loadContent)
   at FModel.Utils.Assets.<>c__DisplayClass3_0.<GetUserSelection>b__0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

My main problem with this is not the fact that it cannot read some files (specifically, texture files), but that theres no option to skip bad/otherwise unreadable files, so batch-exporting is not possible, since exporting halts as soon as one file is found to be unreadable. Please fix this, or at least make it an option to be able to skip wrong files.

**Comment by iAmAsval** [comment]
the main problem with the current fmodel is that if your game doesn't use the latest UE version, the user can't override some part of the code and fmodel struggle to auto detect what version to use
this is the issue here and is fixed for the next fmodel release

**Comment by MrGazdag** [comment]
Thank you for the quick response, yes, the game i'm trying to open is indeed in UE4.22. Is there an ETA for the next release?

**Comment by iAmAsval** [comment]
no eta, it's a big update

**Comment by MrGazdag** [comment]
Ah okay, though I would still recommend making it a toggleable setting to skip files which cannot be read, since if any bugs occur in your code, then it could be ignored, thus making it somewhat future-proof
