### ISSUE TITLE
Head Animation export error FMODEL 

### ISSUE THREAD

**Issue by ItsSharpiez** [iAmAsval/FModel#217]
### Game

Fortnite

### Error

```shell
2021-11-25 23:47:31 [FModel] [INF] IoStore "pakchunk1005-WindowsClient.utoc": 259 files (259 encrypted), mount point: "FortniteGame/Content/", version 3 in 00:00:00.0001829
2021-11-25 23:47:31 [FModel] [INF] {"ShowChangelog":false,"OutputDirectory":"C:\\Build\\FortressArtSource\\assets","GameDirectory":"G:\\Program Files (x86)\\Fortnite\\Fortnite\\FortniteGame\\Content\\Paks","LastOpenedSettingTab":0,"IsAutoExportData":false,"IsAutoSaveProps":false,"IsAutoSaveTextures":true,"IsAutoSaveAnimations":true,"IsAutoOpenSounds":true,"IsAutoOpenMeshes":true,"IsLoggerExpanded":true,"AesKeys":{"FortniteGame":{"Version":"++Fortnite+Release-18.40-CL-18163738-Windows","MainKey":"0x9B0FB282D119754EA74895CDCCAD8DF16252B969718C0A6E7AE74C0F21080F24","DynamicKeys":[{"FileName":"FortniteGame/Content/Paks/pakchunk1002optional-WindowsClient.pak","Guid":"360CD59F6F7B68A441DDED9DB5FD13D7","Key":"0x1BAA5501FFEE9751CF621EACD8CD65F06E219FADA377091C6DE81E2E8C4BED8D","$type":"DynamicKey"},{"FileName":"FortniteGame/Content/Paks/pakchunk1001-WindowsClient.pak","Guid":"23280A6FC0902B6420BB82522AE16D2C","Key":"0x0BBA3A9B6BC9258F9758A774B7560B04F54B60232035BB75D1DFE2B71E568E77","$type":"DynamicKey"},{"FileName":"FortniteGame/Content/Paks/pakchunk1013-WindowsClient.pak","Guid":"D14FDB2BB2FB7746797F25470913BFF1","Key":"0x0900E023170D9C0A146E84278DA7D9018BD5ED4A97F8D79F1935C57779BEA057","$type":"DynamicKey"},{"FileName":"FortniteGame/Content/Paks/pakchunk1004-WindowsClient.pak","Guid":"6DEBEC4266A3BC248F8A8FD4B76878BF","Key":"0xC2308027D55A4E18137DBBD47AD0845901628B91A675F3F0142BF12EFE62A7F8","$type":"DynamicKey"},{"FileName":"FortniteGame/Content/Paks/pakchunk1014-WindowsClient.pak","Guid":"D24667CC40ED6564CE26A31E63E327BA","Key":"0x3A78215B22C6FC8404C78E4FB6611C9AA007B9589652C4D20D0DF5120461C993","$type":"DynamicKey"},{"FileName":"FortniteGame/Content/Paks/pakchunk1005optional-WindowsClient.pak","Guid":"6EA156BE3D18E1D649D7D4B3F8C0FACA","Key":"0xA80283F6833CBB822F51C29B45E1D331A2E0EC6B472C17279B3F3EFAFC3007AA","$type":"DynamicKey"},{"FileName":"FortniteGame/Content/Paks/pakchunk1006optional-WindowsClient.pak","Guid":"87F01091E4DA4FE3FFC9AD92A20A8DCE","Key":"0xA7EE50BE5404579416D9042B216AC39E7B6184D37D574C172BE65D9A2C3BD6ED","$type":"DynamicKey"},{"FileName":"FortniteGame/Content/Paks/pakchunk1008-WindowsClient.pak","Guid":"A062151202F2D5FCAD103D17B9300CE2","Key":"0x262891D3114D876D0244B0D637FB5F8DA7A8A36C9B029775850077EB8FE2B937","$type":"DynamicKey"}],"HasDynamicKeys":true,"$type":"AesResponse"}},"AudioDeviceId":null,"AudioPlayerVolume":50,"LoadingMode":"All","UpdateMode":"Beta","KeepDirectoryStructure":true,"CompressedAudioMode":"PlayDecompressed","AesReload":"OncePerDay","DiscordRpc":"Always","AssetLanguage":"English","CosmeticStyle":"Default","CosmeticDisplayAsset":false,"ImageMergerMargin":5,"Presets":{"Unknown":"Hand Made","FortniteGame":"Hand Made","ShooterGame":"Hand Made","DeadByDaylight":"Hand Made","OakGame":"Hand Made","Dungeons":"Hand Made","WorldExplorers":"Hand Made","g3":"Hand Made","StateOfDecay2":"Hand Made","Prospect":"Hand Made","Indiana":"Hand Made","RogueCompany":"Hand Made","SwGame":"Hand Made","Platform":"Hand Made","BendGame":"Hand Made","TslGame":"Hand Made","PortalWars":"Hand Made","Gameface":"Hand Made"},"OverridedGame":{"Unknown":"GAME_UE4_27","FortniteGame":"GAME_UE4_27","ShooterGame":"GAME_Valorant","DeadByDaylight":"GAME_UE4_27","OakGame":"GAME_Borderlands3","Dungeons":"GAME_UE4_27","WorldExplorers":"GAME_UE4_27","g3":"GAME_UE4_22","StateOfDecay2":"GAME_StateOfDecay2","Prospect":"GAME_UE4_27","Indiana":"GAME_UE4_27","RogueCompany":"GAME_RogueCompany","SwGame":"GAME_UE4_27","Platform":"GAME_UE4_25","BendGame":"GAME_UE4_11","TslGame":"GAME_PlayerUnknownsBattlegrounds","PortalWars":"GAME_UE4_27","Gameface":"GAME_GTATheTrilogyDefinitiveEdition"},"OverridedUEVersion":{"Unknown":"VER_UE4_DETERMINE_BY_GAME","FortniteGame":"VER_UE4_DETERMINE_BY_GAME","ShooterGame":"VER_UE4_DETERMINE_BY_GAME","DeadByDaylight":"VER_UE4_DETERMINE_BY_GAME","OakGame":"VER_UE4_DETERMINE_BY_GAME","Dungeons":"VER_UE4_DETERMINE_BY_GAME","WorldExplorers":"VER_UE4_DETERMINE_BY_GAME","g3":"VER_UE4_DETERMINE_BY_GAME","StateOfDecay2":"VER_UE4_DETERMINE_BY_GAME","Prospect":"VER_UE4_DETERMINE_BY_GAME","Indiana":"VER_UE4_DETERMINE_BY_GAME","RogueCompany":"VER_UE4_DETERMINE_BY_GAME","SwGame":"VER_UE4_DETERMINE_BY_GAME","Platform":"VER_UE4_DETERMINE_BY_GAME","BendGame":"VER_UE4_DETERMINE_BY_GAME","TslGame":"VER_UE4_DETERMINE_BY_GAME","PortalWars":"VER_UE4_DETERMINE_BY_GAME","Gameface":"VER_UE4_DETERMINE_BY_GAME"},"OverridedCustomVersions":{"Unknown":null,"FortniteGame":null,"ShooterGame":null,"DeadByDaylight":null,"OakGame":null,"Dungeons":null,"WorldExplorers":null,"g3":null,"StateOfDecay2":null,"Prospect":null,"Indiana":null,"RogueCompany":null,"SwGame":null,"Platform":null,"BendGame":null,"TslGame":null,"PortalWars":null,"Gameface":null},"OverridedOptions":{"Unknown":null,"FortniteGame":null,"ShooterGame":null,"DeadByDaylight":null,"OakGame":null,"Dungeons":null,"WorldExplorers":null,"g3":null,"StateOfDecay2":null,"Prospect":null,"Indiana":null,"RogueCompany":null,"SwGame":null,"Platform":null,"BendGame":null,"TslGame":null,"PortalWars":null,"Gameface":null},"CustomDirectories":{"Unknown":[],"FortniteGame":[{"Header":"Cosmetics","DirectoryPath":"FortniteGame/Content/Athena/Items/Cosmetics","Error":"","HasErrors":false,"$type":"CustomDirectory"},{"Header":"Emotes [AUDIO]","DirectoryPath":"FortniteGame/Content/Athena/Sounds/Emotes","Error":"","HasErrors":false,"$type":"CustomDirectory"},{"Header":"Music Packs [AUDIO]","DirectoryPath":"FortniteGame/Content/Athena/Sounds/MusicPacks","Error":"","HasErrors":false,"$type":"CustomDirectory"},{"Header":"Weapons","DirectoryPath":"FortniteGame/Content/Athena/Items/Weapons","Error":"","HasErrors":false,"$type":"CustomDirectory"},{"Header":"Strings","DirectoryPath":"FortniteGame/Content/Localization","Error":"","HasErrors":false,"$type":"CustomDirectory"}],"ShooterGame":[{"Header":"Audio","DirectoryPath":"ShooterGame/Content/WwiseAudio/Media/","Error":"","HasErrors":false,"$type":"CustomDirectory"},{"Header":"Characters","DirectoryPath":"ShooterGame/Content/Characters/","Error":"","HasErrors":false,"$type":"CustomDirectory"},{"Header":"Gun Buddies","DirectoryPath":"ShooterGame/Content/Equippables/Buddies/","Error":"","HasErrors":false,"$type":"CustomDirectory"},{"Header":"Cards and Sprays","DirectoryPath":"ShooterGame/Content/Personalization/","Error":"","HasErrors":false,"$type":"CustomDirectory"},{"Header":"Shop Backgrounds","DirectoryPath":"ShooterGame/Content/UI/OutOfGame/MainMenu/Store/Shared/Textures/","Error":"","HasErrors":false,"$type":"CustomDirectory"},{"Header":"Weapon Renders","DirectoryPath":"ShooterGame/Content/UI/Screens/OutOfGame/MainMenu/Collection/Assets/Large/","Error":"","HasErrors":false,"$type":"CustomDirectory"}],"DeadByDaylight":[],"OakGame":[],"Dungeons":[{"Header":"Levels","DirectoryPath":"Dungeons/Content/data/Lovika/Levels","Error":"","HasErrors":false,"$type":"CustomDirectory"},{"Header":"Friendlies","DirectoryPath":"Dungeons/Content/Actor/Characters/Friendlies","Error":"","HasErrors":false,"$type":"CustomDirectory"},{"Header":"Skins","DirectoryPath":"Dungeons/Content/Actor/Characters/Player/Master/Skins","Error":"","HasErrors":false,"$type":"CustomDirectory"},{"Header":"Strings","DirectoryPath":"Dungeons/Content/Localization/","Error":"","HasErrors":false,"$type":"CustomDirectory"}],"WorldExplorers":[{"Header":"Loot","DirectoryPath":"WorldExplorers/Content/Loot/","Error":"","HasErrors":false,"$type":"CustomDirectory"},{"Header":"Strings","DirectoryPath":"WorldExplorers/Content/Localization/","Error":"","HasErrors":false,"$type":"CustomDirectory"}],"g3":[{"Header":"Cosmetics","DirectoryPath":"g3/Content/Blueprints/Cosmetics/","Error":"","HasErrors":false,"$type":"CustomDirectory"},{"Header":"Strings","DirectoryPath":"g3/Content/Localization/","Error":"","HasErrors":false,"$type":"CustomDirectory"}],"StateOfDecay2":[],"Prospect":[],"Indiana":[],"RogueCompany":[],"SwGame":[],"Platform":[],"BendGame":[],"TslGame":[],"PortalWars":[],"Gameface":[]},"LastAesReload":"2021-11-25T00:00:00.0000000-05:00","LastAuthResponse":{"AccessToken":"","ExpiresAt":"2021-11-25T19:39:02.3439962-05:00","$type":"AuthResponse"},"DirLeftTab":{"Key":"A","Modifiers":"None","Error":"","HasErrors":false,"$type":"Hotkey"},"DirRightTab":{"Key":"D","Modifiers":"None","Error":"","HasErrors":false,"$type":"Hotkey"},"AssetLeftTab":{"Key":"Q","Modifiers":"None","Error":"","HasErrors":false,"$type":"Hotkey"},"AssetRightTab":{"Key":"E","Modifiers":"None","Error":"","HasErrors":false,"$type":"Hotkey"},"AssetAddTab":{"Key":"T","Modifiers":"Control","Error":"","HasErrors":false,"$type":"Hotkey"},"AssetRemoveTab":{"Key":"W","Modifiers":"Control","Error":"","HasErrors":false,"$type":"Hotkey"},"AutoExportData":{"Key":"F1","Modifiers":"None","Error":"","HasErrors":false,"$type":"Hotkey"},"AutoSaveProps":{"Key":"F2","Modifiers":"None","Error":"","HasErrors":false,"$type":"Hotkey"},"AutoSaveTextures":{"Key":"F3","Modifiers":"None","Error":"","HasErrors":false,"$type":"Hotkey"},"AutoSaveAnimations":{"Key":"F6","Modifiers":"None","Error":"","HasErrors":false,"$type":"Hotkey"},"AutoOpenSounds":{"Key":"F7","Modifiers":"None","Error":"","HasErrors":false,"$type":"Hotkey"},"AutoOpenMeshes":{"Key":"F6","Modifiers":"None","Error":"","HasErrors":false,"$type":"Hotkey"},"AddAudio":{"Key":"N","Modifiers":"Control","Error":"","HasErrors":false,"$type":"Hotkey"},"PlayPauseAudio":{"Key":"K","Modifiers":"None","Error":"","HasErrors":false,"$type":"Hotkey"},"PreviousAudio":{"Key":"J","Modifiers":"None","Error":"","HasErrors":false,"$type":"Hotkey"},"NextAudio":{"Key":"L","Modifiers":"None","Error":"","HasErrors":false,"$type":"Hotkey"},"MeshExportFormat":"ActorX","LodExportFormat":"FirstLod","SaveSkeletonAsMesh":false,"TextureExportFormat":"Png","Error":"","HasErrors":false,"$type":"UserSettings"}
2021-11-25 23:47:31 [FModel] [INF] ["GET"] [OK(200)] 'https://benbot.app/api/v1/mappings'
2021-11-25 23:47:32 [FModel] [INF] Successfully downloaded oodle dll at "oo2core_9_win64.dll"
2021-11-25 23:47:33 [FModel] [INF] Sharp#1000 (211561520587472898) is now ready
2021-11-25 23:47:33 [FModel] [INF] ["GET"] [OK(200)] 'https://benbot.app/api/v1/hotfixes'
2021-11-25 23:47:42 [FModel] [INF] User DOUBLE-CLICKED to extract 'FortniteGame/Content/Characters/Player/Male/Medium/Heads/M_MED_Nucleus_Head/Meshes/Male_Medium_Nucleus_Head_Facial_Poses.uasset'
2021-11-25 23:47:42 [FModel] [ERR] System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at CUE4Parse_Conversion.Animations.AnimConverter.ConvertAnims(USkeleton skeleton, UAnimSequence animSequence)
   at CUE4Parse_Conversion.Animations.AnimExporter..ctor(USkeleton skeleton, UAnimSequence animSequence)
   at CUE4Parse_Conversion.Animations.AnimExporter..ctor(UAnimSequence animSequence)
   at CUE4Parse_Conversion.Exporter..ctor(UObject export, ETextureFormat textureFormat, ELodFormat lodFormat, EMeshFormat meshFormat)
   at FModel.ViewModels.CUE4ParseViewModel.SaveExport(UObject export)
   at FModel.ViewModels.CUE4ParseViewModel.CheckExport(UObject export)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at FModel.ViewModels.CUE4ParseViewModel.Extract(String fullPath, Boolean addNewTab, Boolean bulkSave)
   at FModel.ViewModels.CUE4ParseViewModel.ExtractSelected(CancellationToken cancellationToken, IEnumerable`1 assetItems)
   at FModel.MainWindow.<>c__DisplayClass18_0.<OnAssetsListMouseDoubleClick>b__0(CancellationToken cancellationToken)
   at FModel.ViewModels.ThreadWorkerViewModel.<>c__DisplayClass20_0.<ProcessQueues>b__0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at FModel.ViewModels.ThreadWorkerViewModel.ProcessQueues()
```

### Reproduction steps

This seems to work fine on older versions of FMODEL but breaks on the latest release.

1. Find a head Animation E.g M_MED_Adam_NT_Head_01_Pose_Export
2. Export said head Animation.
3.  Receive error [ERR] Object reference not set to an instance of an object.
      at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
4. Head Animation not exported 
![image](https://user-images.githubusercontent.com/68305461/143690268-5b20d39a-df0d-4a51-9293-abc6a437bece.png)

**Comment by Tectors** [comment]
Have you tried it on any other head animation?

**Comment by ItsSharpiez** [comment]
Ever head im trying seems to not work.

**Comment by MinshuG** [comment]
It's already fixed. if you build dev branch you will be able to export head animations.
