### ISSUE TITLE
Its 2 errors and i need help

### ISSUE THREAD

**Issue by yordanBUL** [iAmAsval/FModel#221]
### Game

Fortnite

### Error

```shell
[ERR] One or more errors occurred. (Couldn't find LoaderGlobalNameHashes chunk in IoStore global.utoc)
      at FModel.ViewModels.CUE4ParseViewModel.<>c__DisplayClass43_0.<LoadVfs>b__0(CancellationToken cancellationToken)
[INF] Mappings pulled from '++Fortnite+Release-19.00-CL-18335626-Windows_oo.usmap'
[ERR] One or more errors occurred. (Couldn't find LoaderGlobalNameHashes chunk in IoStore global.utoc)
      at FModel.ViewModels.CUE4ParseViewModel.<>c__DisplayClass43_0.<LoadVfs>b__0(CancellationToken cancellationToken)
[INF] 34 localized resources loaded for 'English'
[WRN] Could not load virtual paths, plugin manifest may not exist
```

### Reproduction steps

Opening .pack
1. Opened Fmodel
2. Tried to open first .pack
3. and give me the last error

Refreshing AES keys
1. Opened Fmode
2. Opened AES Manager
3. Then Refresh, Then Ok
4. And here is the error
P.S. If it has a fix please tell me i need to know

**Comment by iAmAsval** [comment]
there's a red message before those errors...
