### ISSUE TITLE
Compression method (Oodle) not detected for PUBG: Battlegrounds v16.2+

### ISSUE THREAD

**Issue by eebAlt** [iAmAsval/FModel#253]
### Game

PUBG: Battlegrounds

### Error

```shell
2022-03-12 07:26:38 [FModel] [WRN] Couldn't create GameFile reader
CUE4Parse.UE4.Exceptions.UnknownCompressionMethodException: Compression method "Unknown" is unknown
   at CUE4Parse.Compression.Compression.Decompress(Byte[] compressed, Int32 compressedOffset, Int32 compressedSize, Byte[] uncompressed, Int32 uncompressedOffset, Int32 uncompressedSize, CompressionMethod method, FArchive reader)
   at CUE4Parse.UE4.Pak.PakFileReader.Extract(VfsEntry entry)
   at CUE4Parse.FileProvider.GameFile.TryCreateReader(FArchive& reader)
```

### Reproduction steps

1. Select PUBG: Test Server and load the game's archives.
2. Attempt to open any compressed asset (i.e. almost any asset).

### Further info
In Update 16.2 of PUBG: Battlegrounds (which was pushed to Test Server on the 8th, and will be pushed to production on the 16th), the compression on all assets has been switched from Zlib to Oodle. FModel, however, does not detect Oodle as being the new compression method, displaying "Unknown", causing all asset reads to fail. I've confirmed that assets can be read correctly if FModel is forced to attempt to use Oodle regardless of the detected compression method, so the issue seems to be with the compression flags.

**Comment by GMatrixGames** [comment]
Adjusted here: https://github.com/FabianFG/CUE4Parse/commit/1fc51feeb4860593814aa4ef42a5ceacc5f59a63
Not a proper solution, but will work for now until a proper solution is done.
